using System.Collections;
using System.Collections.Generic;
using Unity.Burst.CompilerServices;
using UnityEngine;

public enum BulletType { Stone, Arrow , Dialysis, Cannon , Missile }

public class projectile : MonoBehaviour
{
    [SerializeField]
    private List<BulletData> bulletdatas; //ï¿½ï¿½Å©ï¿½ï¿½ï¿½Íºï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ® ï¿½Ş¾Æ¿ï¿½

    [SerializeField]
    private GameObject bulletprefab;
    public float Speed = 1.0f; //ï¿½ï¿½ï¿½Çµï¿½
    public int bulletcount = 0; //Ä«ï¿½ï¿½Æ®ï¿½ï¿½
    public bool isbullet = false; //ï¿½ï¿½ï¿½ï¿½Ã¼Å©
    public float fireInterval = 0.2f; // ï¿½ß»ï¿½ ï¿½ï¿½ï¿½ï¿½
    public BulletType bulletTypeToUse = BulletType.Stone;



    public Animator animator;  //ï¿½ï¿½ï¿½ï¿½Ã¼ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ® ï¿½Ö´Ï¸ï¿½ï¿½Ì¼ï¿½
    private AudioSource _source; //ï¿½ï¿½ï¿½ï¿½Ã¼ ï¿½ï¿½ï¿½ï¿½ï¿?
    private AudioClip _clip; //ï¿½ï¿½Æ®ï¿½ï¿½ï¿½ï¿½

    public float rayDistance = 20; //ï¿½ï¿½ï¿½ï¿½Ã¼ ï¿½ï¿½ï¿½ï¿½ ï¿½Å¸ï¿½
    public LayerMask targetLayer;

    public bool isWallHit = false; //ï¿½ï¿½ ï¿½æµ¹ ï¿½ï¿½ï¿½ï¿½ 
    public bool iscastlehit = false; //ï¿½ï¿½ ï¿½æµ¹ ï¿½ï¿½ï¿½ï¿½

   
    // Start is called before the first frame update
    void Start()
    {
        if (isbullet)
        {
            StartCoroutine(FireBullets());
        }

    }

    // Update is called once per frame
    void Update()
    {
        Vector2 dir = Vector2.left; //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ì»ï¿½ï¿½ï¿½

        RaycastHit2D[] hit2D = Physics2D.RaycastAll(transform.position, dir, rayDistance, targetLayer);


        Debug.DrawRay(transform.position, dir * rayDistance, Color.red); //ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½×¿ï¿?ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ì°ï¿½ï¿½Ï´ï¿½ ï¿½Úµï¿½

        foreach (RaycastHit2D hit in hit2D)
        {
            Debug.Log("ì¶©ëŒ???ï¿½ë¸Œ?ï¿½íŠ¸: " + hit.collider.name);
            if (hit.collider.CompareTag("Wall"))
            {
                Debug.Log("ï¿?ì¶©ëŒ");
                break; //   Å½ ß´ï¿?
            }

            if (hit.collider.CompareTag("Castle"))
            {
                Debug.Log("??ì¶©ëŒ");
            }
        }

    }
    IEnumerator FireBullets()
    {
        for (int i = 0; i < bulletcount; i++)
        {
            SpwawnBullet(bulletTypeToUse);
            yield return new WaitForSeconds(fireInterval);
        }
    }
    public void SpwawnBullet(BulletType type)
    {
        if (bulletdatas == null || bulletdatas.Count == 0 || (int)type >= bulletdatas.Count)
        {
            Debug.LogError("Bullet data is not properly set up!");
            return;
        }

        GameObject bulletObj = Instantiate(bulletprefab, transform.position, Quaternion.identity);
        Bullet bullet = bulletObj.GetComponent<Bullet>();
        if (bullet != null)
        {
            bullet.bulletData = bulletdatas[(int)type];
        }
    }
}
